website:
  title: "TASSN"
  favicon: ../favicon.ico
  
  navbar:
    pinned: true
    left:
      - href: home.qmd
        text: Inicio
      - href: about.qmd
        text: Acerca de
    right: 
      - text: "{{< iconify bi instagram size=1.1em title='Instagram' >}}"
        href: "https://www.instagram.com/transasylumsupport/"
      - text: "{{< iconify bi facebook size=1.1em title='Facebook' >}}"
        href: "https://www.facebook.com/transasylumsupport"
      - text: "{{< iconify bi heart size=1.1em title='Donar en Givebutter' >}}"
        href: "https://givebutter.com/tassnxsupport?fbclid=PAZXh0bgNhZW0CMTEAAae6Q6dFJYk8SBKfZ6N8h_6Fq8Bs39Ia1_UzYYdyzTFzS3tCP7N1ZQXP4sxmdQ_aem_sPESXx_pZo_IXHukFaFx9Q"
      - text: "{{< iconify bi envelope size=1.1em title='Correo electr√≥nico' >}}"
        href: "mailto:give.2.tassn@gmail.com"
      - text: "üåê Idioma"
        menu:
          - text: "English"
            href: ../
          - text: "Espa√±ol"
            href: ./

  page-footer:
    left: |
      <span class="faux-block">Todo el contenido est√° licenciado bajo<br>[{{< fa brands creative-commons >}}{{< fa brands creative-commons-by >}} Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>
    background: light

  sidebar: 
    style: floating

lang: es

format:
  html:
    theme: default
    css: ../styles.css
    toc: true
    toc-location: left